document.write('<div class="nav-container-fixed">');
document.write('                <div class="nav-inner">');
document.write('                    <div class="logo-and-nav">');
document.write('                        <a href="/web.ollieblox.com/home.html"><div class="logo"></div></a>');
document.write('                    </div>');
document.write('                    <div class="page-selections">');
document.write('                        <a href="games" class="page-a"><button class="pages white">Games</button></a>');
document.write('                        <a href="games" class="page-a"><button class="pages white">Catalog</button></a>');
document.write('                        <a href="games" class="page-a"><button class="pages white">Develop</button></a>');
document.write('                        <a href="games" class="page-a"><button class="pages white">OLLIEBUX</button></a>');
document.write('                    </div>');
document.write('                </div>');
document.write('            </div>');
